### ISSUE TITLE
[Entrega 3] Relación entre Eventos y Hospedaje

### ISSUE THREAD

**Issue by verobaeza** [IIC2413/Syllabus-2022-2#223]
Hola, estoy resolviendo el punto de la navegación para los artistas que pide "Dónde se van a quedar durante el evento y el tipo de traslado". Hice una query que busca donde coinciden:
-fecha de inicio del evento y fecha de inicio del hospedaje
-ciudad del evento y lugar del hospedaje
Sin embargo no arroja ningún resultado (para ningún evento de cualquier artista). Revisé las tablas originales y hasta ahora no he encontrado ningún par de tuplas de ambas tablas que estén relacionadas mediante las condiciones que puse arriba., entonces ¿mediante qué atributos se relacionan los datos de eventos con los de hospedaje y traslado?

Gracias

**Comment by IgnacioLanderos** [comment]
Nos pasó lo mismo, no encontramos ninguna manera de relacionar aquellas tablas

**Comment by drodrguez** [comment]
"En la parte 2.2 de navegación, específicamente en la parte de los Artistas, el cuarto punto que dice "Dónde se van a quedar durante el evento y el tipo de traslado." se va a cambiar por "Mostrar los lugares en donde se han hospedado junto con el tipo de traslado", pero no tienen que tener relación con eventos. Por ejemplo, podrían crear una pestaña en donde muestren todos los eventos con la información que se les pide (punto 1,2,3,5), y una pestaña aparte que muestre todos los hospedajes y alojos que ha tenido el artista (los cuales, vuelvo a repetir, NO tienen relación con los eventos)."

Mandaron un anuncio con esta información hace un par de días.

**Comment by verobaeza** [comment]
Se me había pasado el anuncio, gracias!
