### ISSUE TITLE
Problemas con conexion a base de datos 

### ISSUE THREAD

**Issue by Franbelen** [IIC2413/Syllabus-2022-2#237]
Hola buenas al conectarnos desde una carpeta "paralela" al conexion.php nos sale este error 
![imagen](https://user-images.githubusercontent.com/101537816/205393598-30b1d4af-3acf-45f9-addb-71d0c7e0337e.png)
pero si nos conectamos desde arriba funciona, intentamos con requiere("../config/conexion.php") y casi toda otra variable de eso y sale ese error 
¿que podría ser?
(también probamos pegando config en la carpeta que íbamos a usarlo aun así no funciona por lo que parece ser un problema en la conexión)

**Comment by catalinasaini** [comment]
Hola! Pudiste solucionar esto? Tenemos el mismo problema.

**Comment by Franbelen** [comment]
Hola si mi compañera lo soluciono, si no me equivoco usamos el codigo de la ayudantia y fallaba y el de la wiki me comento mi compañera que servia, espero ayude
