### ISSUE TITLE
[T2] Request de categorías de la API?

### ISSUE THREAD

**Issue by NicoJGutierrez** [IIC2413/Syllabus-2022-2#245]
Hola! Estoy viendo el tema del drop down de las categorías de los productos en la API, y parece que a la API le podría faltar una request que permita revisar las categorías de los productos, aunque se intuye que no debería haber una request así a partir de esta parte del enunciado:

![image](https://github.com/IIC2413/Syllabus-2022-2/assets/80768621/b1ca99ff-8b44-4d94-adbf-e56002418890)
(no hay una evaluación del uso de un endpoint para obtener los datos de las categorías)

Entonces, se tendría que armar eso sin una request especial, simplemente filtrando los datos en "get products", o se debe hacer de otra manera?

Gracias de antemano!

**Comment by NicoJGutierrez** [comment]
En el código se explica que sólo tenemos que hacer una request y el filtrado ya está hecho:
![image](https://github.com/IIC2413/Syllabus-2022-2/assets/80768621/f32cf7da-aa5b-47db-8660-1797d2b3d241)
Perdón por las molestias.

**Comment by aerotecnia99** [comment]
Hola @NicoJGutierrez , estás haciendo la issue en el repo equivocado, este es del 2022-2, debería ser en las issues del 2023-2 👀
