### ISSUE TITLE
Plazo Control

### ISSUE THREAD

**Issue by ArianaCisternas** [IIC2413/Syllabus-2022-2#28]
Buenos días, 

Esperando que tengan un buen día, como curso conversamos que nos gustaría tener más plazo para realizar el primer control, principalmente debido a la gran cantidad de tareas para el día de hoy y carga académica en general. Con más plazo, esperamos poder hacer el control con mayor tranquilidad y dedicación.

Atentamente,

Ariana

**Comment by Matrolfeis123** [comment]
Hola, me sumo al comentario, hoy tengo 2 entregas y no me alcanzará el tiempo :(

**Comment by fvalenzuelg** [comment]
Hola yo igual me sumo a la petición de más plazo :( por favor tengo muchas entregas

**Comment by FabriRandon** [comment]
Me sumo a la petición

**Comment by cristobal-morales-l** [comment]
Me sumo a la petición!
