### ISSUE TITLE
Problemas ingreso servidor

### ISSUE THREAD

**Issue by Amandasandov** [IIC2413/Syllabus-2022-2#53]
Hola. Hoy ingrese al servidor y cambie la contraseña como es indicado en la wiki del curso pero ahora me trato de meter y me sale que la contraseña incorrecta. Lo único que se ocurre que puede haber pasado es que escribi mal la contraseña pero sería raro porque me tendría que haber equivocado en los mismo 2 veces. De cualquier manera, ahora no podemos ingresar al servidor y necesitamos ayuda. De antemano muchas gracias por su ayuda.

**Comment by franancic** [comment]
Solucionado:)
