### ISSUE TITLE
Cambiar atributos de una tabla

### ISSUE THREAD

**Issue by BenitoOl** [IIC2413/Syllabus-2022-2#66]
![image](https://user-images.githubusercontent.com/69522774/189743058-8c44512f-a152-46ff-9e15-0b175c9ea96e.png)
Hola ! queria saber como cambiar atributos de una tabla, como ejemplo si tengo la tabla artista con nombre definido como DATE y quiero cambiarlo a VARCHAR(15) como seria? usando el comando \h ALTER TABLE salen varios comandos con alter table pero no entiendo como ponerlos, dejo imagen del que creo debo usar.

**Comment by vicentethomas** [comment]
Hola! 
Prueba con
```sql
ALTER TABLE artista ALTER COLUMN nombre TYPE VARCHAR(15)
```
Esto sigue el siguiente formato (para que lo puedas usar con cualquier tabla)
```sql
ALTER TABLE nombre_tabla ALTER COLUMN nombre_columna TYPE tipo_dato
```
